// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvPNQyf00UYtRZ-Q9sbPbZx5xAiMRrT2Y',
    appId: '1:704520395532:web:3f92774c6375ce6cab0729',
    messagingSenderId: '704520395532',
    projectId: 'quanlytroapp',
    authDomain: 'quanlytroapp.firebaseapp.com',
    storageBucket: 'quanlytroapp.firebasestorage.app',
    measurementId: 'G-X0JQ3BLMH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzq4ifYON2vpMnenmlsXdKYflPYx-ckMg',
    appId: '1:704520395532:android:8e4e43624dac57d2ab0729',
    messagingSenderId: '704520395532',
    projectId: 'quanlytroapp',
    storageBucket: 'quanlytroapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLbrDyMtEOG0auvZYwJlhF3CEH2Yx1wRo',
    appId: '1:704520395532:ios:e9b0276f515f1ce5ab0729',
    messagingSenderId: '704520395532',
    projectId: 'quanlytroapp',
    storageBucket: 'quanlytroapp.firebasestorage.app',
    iosBundleId: 'com.example.qlphongtro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLbrDyMtEOG0auvZYwJlhF3CEH2Yx1wRo',
    appId: '1:704520395532:ios:e9b0276f515f1ce5ab0729',
    messagingSenderId: '704520395532',
    projectId: 'quanlytroapp',
    storageBucket: 'quanlytroapp.firebasestorage.app',
    iosBundleId: 'com.example.qlphongtro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvPNQyf00UYtRZ-Q9sbPbZx5xAiMRrT2Y',
    appId: '1:704520395532:web:6cdef1921adacb00ab0729',
    messagingSenderId: '704520395532',
    projectId: 'quanlytroapp',
    authDomain: 'quanlytroapp.firebaseapp.com',
    storageBucket: 'quanlytroapp.firebasestorage.app',
    measurementId: 'G-E3RCSHY9K6',
  );
}
